services:
  - type: web
    name: kamikaze
    runtime: docker
    plan: standard
    autoDeploy: true
    dockerfilePath: servers/kamikaze/Dockerfile
    buildFilter:
      paths:
        - servers/kamikaze/**/*.ts
        - contracts/bofio/**/*.ts
        - packages/tsconfig/*.json
    envVars:
      - fromGroup: servers/kamikaze
      - key: DATABASE_URL
        fromDatabase:
          name: kamikazeDB
          property: connectionString
    domains:
      - "v1.api.gateway.saitama.fun"
  - type: web
    name: bird 
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: bun run build
    startCommand: bun run migrate && bun run start
    buildFilter:
      paths:
        - servers/bird/**/*.ts
        - packages/tsconfig/*.json
    envVars:
      - fromGroup: servers/bird 
      - key: DATABASE_URL
        fromDatabase:
          name: birdDB
          property: connectionString 
      - key: APP_URL
        fromService:
          type: web
          name: exma
          envVarKey: RENDER_EXTERNAL_URL
    domains: 
      - "bot.gateway.saitama.fun"
      
  # - type: worker
  #   name: watchdog
  #   runtime: docker
  #   plan: starter
  #   autoDeploy: true
  #   dockerfilePath: servers/watchdog/Dockerfile
  #   buildFilter:
  #     paths:
  #       - contracts/bofio/**/*.ts
  #       - servers/watchdog/**/*.ts
  #       - servers/kamikaze/src/db/*.sql
  #       - servers/kamikaze/drizzle/*.json
  #       - servers/kamikaze/src/modules/payment/**/*.ts
  #       - servers/kamikaze/src/modules/webhook/**/*.ts
  #   envVars:
  #     - fromGroup: servers/kamikaze
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: kamikazeDB
  #         property: connectionString
  - type: web
    name: exma
    runtime: docker
    plan: standard
    autoDeploy: true
    dockerfilePath: apps/exma/Dockerfile
    buildFilter:
      paths:
        - apps/exma/**/*.ts
        - packages/tsconfig/*.json
        - packages/wallet/**/*.ts
        - contracts/bofio/**/*.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: SAITAMA_API_URL
        fromService:
          type: web
          name: kamikaze
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXT_PUBLIC_SAITAMA_API_URL
        fromService:
          type: web
          name: kamikaze
          envVarKey: RENDER_EXTERNAL_URL
    domains:
      - wallet.saitama.fun
databases:
  - name: kamikazeDB
    databaseName: kamikaze
    user: admin
    plan: starter
  - name: birdDB
    databaseName: bird
    user: admin
    plan: starter
