[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bofoi = "8Kc1XgpHpMEqC8nTEAzqXU61m9drjrEujLGMgDwXfk9r"

[programs.devnet]
bofoi = "8Kc1XgpHpMEqC8nTEAzqXU61m9drjrEujLGMgDwXfk9r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/macbookpro/.config/solana/id.json"

[scripts]
test = "bun x ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
